# Generated by Django 5.2.6 on 2026-02-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_admin_viktim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='viktim',
        ),
    ]
